---
- name: Init a new swarm with default parameters
  docker_swarm:
    state: present
    advertise_addr: "{{ swarm_internal_ip_addr }}"
    remote_addrs: ["{{ swarm_init_manager_ip }}:2377"]
  when:
    - primarymanager is defined

- name: Get Docker Manager Join Token
  register: manager_join_token
  shell: docker swarm join-token manager | grep 'token'|awk '{print($5)}'
  changed_when: false
  when:
    - primarymanager is defined

- name: "Add Docker Manager Join Token to dummy host"
  add_host:
    name: "DOCKER_SWARM_MANAGER_TOKEN_HOLDER"
    token: "{{ manager_join_token.stdout }}"
    hash:
  when:
    - primarymanager is defined
  changed_when: false

- name: Get Docker Worker Join Token
  register: worker_join_token
  shell: docker swarm join-token worker | grep 'token'|awk '{print($5)}'
  changed_when: False
  when:
    - primarymanager is defined

- name: "Add Docker Worker Join Token to dummy host"
  add_host:
    name: "DOCKER_SWARM_WORKER_TOKEN_HOLDER"
    token: "{{ worker_join_token.stdout }}"
    hash:
  when: worker_join_token.stdout is defined
  changed_when: false

- name: Add manager node
  docker_swarm:
    state: join
    advertise_addr: "{{ swarm_internal_ip_addr }}"
    join_token: "{{ hostvars['DOCKER_SWARM_MANAGER_TOKEN_HOLDER']['token'] }}"
    remote_addrs: ["{{ swarm_init_manager_ip }}:2377"]
  when:
    - primarymanager is undefined
    - swarm_role == 'manager'

- name: Add worker node
  docker_swarm:
    state: join
    advertise_addr: "{{ swarm_internal_ip_addr }}"
    join_token: "{{ hostvars['DOCKER_SWARM_WORKER_TOKEN_HOLDER']['token'] }}"
    remote_addrs: ["{{ swarm_init_manager_ip }}:2377"]
  when:
    - primarymanager is undefined
    - swarm_role == 'worker'
